POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "omar",
    "password": "omar"
}


###
POST http://127.0.0.1:8000/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTkwMjI2LCJpYXQiOjE3NDI5ODk5MjYsImp0aSI6ImMzZmQyYjRkNjM4YTQ3NTE4NGNiNDhlNDE4NjFmNTFiIiwidXNlcl9pZCI6MX0.eUPHENkp9iO13xvbA9n6-YYbAB5JDzAQbjy26N4oqGI
Content-Type: application/json

{
    "name": "New Topic By Omar",
    "topic_id": 1,
    "expire": "2025-03-30"
}

###
GET http://127.0.0.1:8000/topics/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTMyODE0LCJpYXQiOjE3NDI5MzI1MTQsImp0aSI6IjUzN2MxMzM1YTI3NDQ4MWRhM2E5NTQwZTM0Y2NlZjdlIiwidXNlcl9pZCI6NH0.yA0TUis0tgF4tgpzPsem5zfiUzOy70oXAvQazlfbwfQ
Content-Type: application/json

{
    "name":"Sara's Topic"
}

###
POST http://127.0.0.1:8000/toggle/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyOTM4NjkzLCJpYXQiOjE3NDI5MzgzOTMsImp0aSI6IjI1Y2FkNWM4MDY1MjQ5MzhhOGM5ZDIxOWUwOWYxMDFmIiwidXNlcl9pZCI6NH0.MqVZFmErj3U--G4PBthXeFFFPhiQExIpTyKeqCEwEhw
Content-Type: application/json

{
    "name":"Sara's Topic"
}



###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username": "sara",
    "email": "sara@sara.com",
    "password": "sara"
}





